package sg.edu.nus.cats.domain.enums;

public enum AuditEventType {
    SUBMITTED,
    UPDATED,
    DELETED,
    APPROVED,
    REJECTED,
    CANCELLED,
    COMPLETED,
    CLAIM_SUBMITTED,
    CLAIM_RESUBMITTED,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    REIMBURSEMENT_RECORDED,
    ENTITLEMENT_CHANGED,
    ROUTING_CHANGED,
    CATALOGUE_CHANGED,
    HOLIDAY_CHANGED,
    STAFF_CREATED,
    STAFF_UPDATED,
    ACCOUNT_DISABLED,
    EMAIL_SENT,
    EMAIL_RETRY
}
