package sg.edu.nus.cats.service;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Clock;
import java.time.LocalDate;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import sg.edu.nus.cats.config.StorageProperties;
import sg.edu.nus.cats.support.BusinessException;
import sg.edu.nus.cats.support.ErrorCode;
import sg.edu.nus.cats.support.Hashing;

/**
 * Private document vault. Files never live in src/main/resources or the web
 * root, the path is generated by the server and every download goes through an
 * ownership check in the claim controller.
 */
@Service
public class DocumentStorageService {

    private static final List<String> FORBIDDEN_EXTENSIONS = List.of("exe", "sh", "bat", "js", "html", "htm");
    private static final int HEADER_LENGTH = 8;

    private final StorageProperties properties;
    private final Clock clock;

    public DocumentStorageService(StorageProperties properties, Clock clock) {
        this.properties = properties;
        this.clock = clock;
    }

    public StoredDocument store(MultipartFile file, Long claimId) {
        if (file == null || file.isEmpty()) {
            throw new BusinessException(ErrorCode.DOCUMENT_MISSING, "Choose a file to upload.");
        }
        if (file.getSize() > properties.getMaxFileSize()) {
            throw new BusinessException(ErrorCode.FILE_TOO_LARGE,
                    "The file is larger than " + properties.getMaxFileSize() / (1024 * 1024) + " MB.");
        }
        String extension = extensionOf(file.getOriginalFilename());
        if (FORBIDDEN_EXTENSIONS.contains(extension)) {
            throw new BusinessException(ErrorCode.INVALID_REQUEST,
                    "Files of type ." + extension + " are not accepted. Upload a PDF or an image.");
        }
        byte[] header = readHeader(file);
        String detected = detectContentType(header);
        if (detected == null) {
            throw new BusinessException(ErrorCode.INVALID_REQUEST,
                    "The file content is not a PDF, JPEG or PNG document.");
        }
        if (!matchesExtension(detected, extension)) {
            throw new BusinessException(ErrorCode.INVALID_REQUEST,
                    "The file content (" + detected + ") does not match the file name (." + extension + ").");
        }

        LocalDate today = LocalDate.now(clock);
        String storageKey = "%d/%02d/claim-%d/%s.%s".formatted(today.getYear(), today.getMonthValue(), claimId,
                UUID.randomUUID(), extension);
        Path target = resolve(storageKey);
        try {
            Files.createDirectories(target.getParent());
            try (InputStream in = file.getInputStream()) {
                Files.copy(in, target, StandardCopyOption.REPLACE_EXISTING);
            }
            byte[] content = Files.readAllBytes(target);
            return new StoredDocument(storageKey, safeName(file.getOriginalFilename(), extension), detected,
                    content.length, Hashing.sha256Hex(content));
        } catch (IOException ex) {
            throw new IllegalStateException("Unable to store the uploaded document", ex);
        }
    }

    /** Opens a stored file. Callers must have checked ownership first. */
    public Resource load(String storageKey) {
        Path path = resolve(storageKey);
        if (!Files.exists(path) || !Files.isReadable(path)) {
            throw new BusinessException(ErrorCode.NOT_FOUND, "The stored document is no longer available.");
        }
        return new FileSystemResource(path);
    }

    public void delete(String storageKey) {
        try {
            Files.deleteIfExists(resolve(storageKey));
        } catch (IOException ex) {
            throw new IllegalStateException("Unable to remove the stored document", ex);
        }
    }

    private Path resolve(String storageKey) {
        Path root = Path.of(properties.getRoot()).toAbsolutePath().normalize();
        Path resolved = root.resolve(storageKey).normalize();
        if (!resolved.startsWith(root)) {
            throw new BusinessException(ErrorCode.ACCESS_DENIED, "The document path is not allowed.");
        }
        return resolved;
    }

    private static String extensionOf(String fileName) {
        if (fileName == null || !fileName.contains(".")) {
            return "";
        }
        return fileName.substring(fileName.lastIndexOf('.') + 1).toLowerCase(Locale.ROOT);
    }

    private static String safeName(String originalName, String extension) {
        if (originalName == null || originalName.isBlank()) {
            return "document." + extension;
        }
        String name = Path.of(originalName).getFileName().toString().replaceAll("[^A-Za-z0-9._-]", "_");
        return name.length() > 120 ? name.substring(name.length() - 120) : name;
    }

    private static byte[] readHeader(MultipartFile file) {
        try (InputStream in = file.getInputStream()) {
            return in.readNBytes(HEADER_LENGTH);
        } catch (IOException ex) {
            throw new BusinessException(ErrorCode.INVALID_REQUEST, "The uploaded file could not be read.");
        }
    }

    private static String detectContentType(byte[] header) {
        if (header.length >= 4 && header[0] == '%' && header[1] == 'P' && header[2] == 'D' && header[3] == 'F') {
            return "application/pdf";
        }
        if (header.length >= 3 && (header[0] & 0xFF) == 0xFF && (header[1] & 0xFF) == 0xD8 && (header[2] & 0xFF) == 0xFF) {
            return "image/jpeg";
        }
        if (header.length >= 8 && (header[0] & 0xFF) == 0x89 && header[1] == 'P' && header[2] == 'N'
                && header[3] == 'G') {
            return "image/png";
        }
        return null;
    }

    private static boolean matchesExtension(String detected, String extension) {
        return switch (detected) {
            case "application/pdf" -> extension.equals("pdf");
            case "image/jpeg" -> extension.equals("jpg") || extension.equals("jpeg");
            case "image/png" -> extension.equals("png");
            default -> false;
        };
    }

    /** Metadata returned by the vault after a successful upload. */
    public record StoredDocument(String storageKey, String originalName, String contentType, long sizeBytes,
            String sha256) {
    }
}
